### ISSUE TITLE
Can not build on Stack

### ISSUE THREAD

**Issue by pdavidow** [turion/rhine#123]
I would like to use Rhine in my own package, using Stack. 

My package.yaml has (among other things):

```
allow-newer: true

dependencies:
- base >= 4.7 && < 5
- rhine
```

and stack.yaml has `extra-deps: [rhine-0.5.0.1]`

But `stack build` gives

```
Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for rhine-0.5.0.1:
    base-4.12.0.0 from stack configuration does not match >=4.9 && <4.12  (latest matching version
                  is 4.11.1.0)
    containers-0.6.0.1 from stack configuration does not match ==0.5.*  (latest matching version
                       is 0.5.11.0)
    dunai-0.5.1 from stack configuration does not match ==0.4.0.*  (latest matching version
                is 0.4.0.0)
    vector-sized-1.2.0.0 from stack configuration does not match >=0.6 && <1.1  (latest matching
                         version is 1.0.4.0)
```

Not sure what to do...

**Comment by turion** [comment]
Can you use `nightly-2018-09-28` in your `stack.yaml` as resolver? Then you don't need `extra-deps: [rhine-0.5.0.1]` anymore and all the versions should work out.

**Comment by pdavidow** [comment]
That worked, but I left `allow-newer: true` in package.yaml. I only put it there to try to make things work, so should I remove it (things seem ok without it).

**Comment by turion** [comment]
Yes, `allow-newer: true` shouldn't be needed if everything works out.
