### ISSUE TITLE
intero not working

### ISSUE THREAD

**Issue by pdavidow** [turion/rhine#124]
I can not get intero to work. I did `stack build intero` in rhine-examples, but `import FRP.Rhine` is not recognized (_Could not find module `FRP.Rhine'_), and hence intero does not function.

These are the steps I took:
```
git clone https://github.com/turion/rhine.git
cd rhine/rhine-examples
stack build
stack build intero
```

(Note that closing the IDE (VSCode) and bringing it up again did not help.)

**Comment by turion** [comment]
What is `intero`? It's not an executable defined in `rhine-examples.cabal`. If it's an executable you defined yourself, you must add `rhine` as a dependency in your `.cabal`.

**Comment by turion** [comment]
Ah I understand now. It's about https://github.com/chrisdone/intero. What documentation did you follow? What libraries does your approach work with?

**Comment by pdavidow** [comment]
I am using the _Haskero_ VSCode extension, which in turn uses _Intero_, as per https://gitlab.com/vannnns/haskero/blob/master/client/doc/installation.md

**Comment by pdavidow** [comment]
Note that this is not a big deal because I can actually copy and paste the rhine-examples into my own package, and _intero_ will work fine other there.
