### ISSUE TITLE
Dunai and Rhine defines identical operators in conflicting ways

### ISSUE THREAD

**Issue by ggreif** [turion/rhine#16]
In `dunai` there are
``` haskell
infixr 4 <-<
infixr 4 >->
```
while in `rhine` the same operators (with identical semantics) are defined as
``` haskell
infixl 6 <-<
infixr 6 >->
```
This can be _maximally_ confusing. Any idea which side should change?

**Comment by ggreif** [comment]
@ivanperez-keera maybe the change should be in `dunai`.

**Comment by turion** [comment]
I'm not aware of any such operators in the _package_ dunai. Where are they defined? Are they in bearriver?

**Comment by turion** [comment]
My bad! Yes, [of course it's there](https://github.com/ivanperez-keera/dunai/blob/39407d26f2535b4550d8f02907045cca5c1a2e5c/src/Control/Arrow/Util.hs#L11). Yep, should be removed in dunai, I think. Closed here and [reopened in dunai](https://github.com/ivanperez-keera/dunai/issues/71).
