### ISSUE TITLE
Segmentation fault when running rhine gloss examples

### ISSUE THREAD

**Issue by madjestic** [turion/rhine#216]
Hey guys,

I am getting a seg.fault when running rhing gloss examples:

```
$ cabal run exe:rhine-gloss-gears
Up to date
Please choose between the pure (1), the pure combined (2), and the IO backend (3):
1
rhine-gloss-gears: mmap 4096 bytes at (nil): Cannot allocate memory
rhine-gloss-gears: Try specifying an address with +RTS -xm<addr> -RTS
Segmentation fault
```
How can I fix that?

Cheers,
Vlad

**Comment by madjestic** [comment]
I am running a gentoo, I did all standard things, cloned the repo, cd'ed into rhine-gloss dir, cabal clean, cabal build, cabal run exe:rhine-gloss-gears.

Options 2 and 3 lead to the same result.

**Comment by madjestic** [comment]
Having said that, I just tried it and it works.  That is weird indeed!

**Comment by madjestic** [comment]
Maybe I had system memory maxed out without noticing and memory allocator was failing, which is fair enough?

**Comment by turion** [comment]
That sounds plausible. Glad it works!

**Comment by turion** [comment]
Maybe it was https://discourse.haskell.org/t/facing-mmap-4096-bytes-at-nil-cannot-allocate-memory-youre-not-alone/6259

**Comment by madjestic** [comment]
Wagh!  I will try that asap!  Thanks!
