### ISSUE TITLE
Schedule SelectClock with main clock

### ISSUE THREAD

**Issue by turion** [turion/rhine#22]
In `FRP.Rhine.Clock.Select`, there is a schedule for two `SelectClock`s of the same main clock, `schedSelectClocks`. There should be a schedule for a `SelectClock` and its main clock.

**Comment by SolviQorda** [comment]
I'm trying to solve this. I'm a beginner and still wrapping my head around Rhine's structure and use of Arrows, but I think I'm getting somewhere. I hope that's ok!

Can I just ask to check I've understood, when you say :
'there needs to be a schedule for `SelectClock' and its main clock',

am I right in reading that as:
the new function need to output a timestamp and an Either value which specifies whether the subclock or the mainClock has ticked?

**Comment by turion** [comment]
You're very welcome to submit a pull request! If there are problems with it, I'll help you with getting the arrow details etc. right.

Yes, you've understood the issue precisely correct. I think maybe we need a `Monoid` instance for the main clock.

Don't worry if the CI fails, that's because of travis issues I'm still working around.

**Comment by SolviQorda** [comment]
Amazing thanks! I'll have a go and try and make a PR soon :+1:

**Comment by SolviQorda** [comment]
When you say 'we maybe need a monoid instance' - do you think that's a separate issue or do you think it's necessary for this function? Would I need to declare that with the other Clock instances in Clock.hs? 

Thank you for any clarification!

**Comment by SolviQorda** [comment]
Hey, so this is where I'm up to so far - is this the right type signature? Also, please could you help me resolve the following error?

```
schedSelectClockAndMain
  :: (Monad m, Monoid cl, Clock m cl)
  => Schedule m cl (SelectClock cl a)
schedSelectClockAndMain = Schedule {..} -- 85
  where
    startSchedule mainClock1 subClock = do
      (runningClock, initialTime) <- startClock
        $ mainClock1 `mappend` mainClock subClock
      let
        runningSelectClock = concatS $ proc _ -> do
          (time, tag) <- runningClock -< ()
          returnA                     -< catMaybes
            [ (time, ) . Left  <$> select mainClock1 tag
            , (time, ) . Right <$> select subClock tag ]
      return (runningSelectClock, initialTime)

```



```
/home/solvi/Development/osprojects/rhineenv/rhine/rhine/src/FRP/Rhine/Clock/Select.hs:85:27: error:
    • Couldn't match type ‘cl’
                     with ‘SelectClock (SelectClock cl0 (Tag cl0)) (Tag cl)’
      ‘cl’ is a rigid type variable bound by
        the type signature for:
          schedSelectClockAndMain :: forall (m :: * -> *) cl.
                                     (Monad m, Monoid cl, Clock m cl) =>
                                     Schedule m cl cl
        at /home/solvi/Development/osprojects/rhineenv/rhine/rhine/src/FRP/Rhine/Clock/Select.hs:83:6
      Expected type: cl
                     -> cl
                     -> m (MSF m () (TimeDomainOf cl, Either (Tag cl) (Tag cl)),
                           TimeDomainOf cl)
        Actual type: SelectClock cl0 (Tag cl0)
                     -> SelectClock (SelectClock cl0 (Tag cl0)) (Tag cl)
                     -> m (MStream m (TimeDomainOf cl0, Either (Tag cl0) (Tag cl)),
                           TimeDomainOf cl0)
    • In the ‘startSchedule’ field of a record
      In the expression: Schedule {..}
      In an equation for ‘schedSelectClockAndMain’:
          schedSelectClockAndMain
            = Schedule {..}
            where
                startSchedule mainClock1 subClock
                  = do { (runningClock, initialTime) <- startClock
                                                        $ mainClock1 `mappend` mainClock subClock;
                         .... }
    • Relevant bindings include
        schedSelectClockAndMain :: Schedule m cl cl
```

**Comment by turion** [comment]
The type signature looks absolutely right!

I think the problem is the line `[ (time, ) . Left  <$> select mainClock1 tag`. Maybe that should be `[ Just (time, Left tag)`? (The main clock has no select function, all its ticks occur.)

**Comment by turion** [comment]
As for style, this looks really good! The only thing that would be great is if you can use [record wild cards](https://ocharles.org.uk/blog/posts/2014-12-04-record-wildcards.html), i.e. `startSchedule mainClock' SelectClock {..} = do`.

**Comment by SolviQorda** [comment]
Thanks @turion that was really useful!

**Comment by turion** [comment]
Thank you for contributing!

**Comment by turion** [comment]
Feel free to tackle any other issues if you want.
