### ISSUE TITLE
Stack caching doesn't work?

### ISSUE THREAD

**Issue by turion** [turion/rhine#314]
https://github.com/turion/rhine/actions/runs/9060039650/job/24888920762 should have created a cache that https://github.com/turion/rhine/actions/runs/9060771796/job/24891180509?pr=313 should have been able to use, but it didn't. This slows down the stack CI jobs considerably.

**Comment by turion** [comment]
@miguel-negrao maybe you have an idea what could be broken? :)

**Comment by miguel-negrao** [comment]
I think I would vote in favor of completely removing stack. cabal does such a good job currently...
