### ISSUE TITLE
Sawtooth example <<loop>> exception

### ISSUE THREAD

**Issue by crocodile-dentist** [turion/rhine#366]
On my linux OS and GHC 9.2.8, running `cabal run Sawtooth` outputs `Sawtooth: <<loop>>` exception, is this a known fault?

**Comment by turion** [comment]
That sounds a lot like a bug, thanks for reporting! I'll have a look when I'm back at a computer.

**Comment by turion** [comment]
Can reproduce.

**Comment by turion** [comment]
The bug was introduced by replacing dunai by automata. Working on a fix.

**Comment by turion** [comment]
(Git bisect gave e89856e28f8c877f2a30baea5b6bc205a2af172e)

**Comment by crocodile-dentist** [comment]
Thank you for fixing the issue.
