### ISSUE TITLE
Implement schedule for Cycle clocks and base Step clock on Cycle

### ISSUE THREAD

**Issue by turion** [turion/rhine#50]
The `FRP.Rhine.Cycle` clocks give an implementation of pure, cyclically repeating clocks:
`CycleClock '[500, 1000]` would tick at `500, 1500, 2000, 3000, 3500` and so on. (See the `CycleClock` example in `rhine-examples`.)

In principle, the clock `Step n` is nothing else than `CycleClock '[n]`, so this should be a type synonym.

But there exists a schedule for `Step n` clocks which doesn't exist yet for `CycleClock`s, so it should be generalised to `CycleClock` and then `Step n` refactored as a synonym.

(Also note #45 )

**Comment by SolviQorda** [comment]
I'm going to attempt this issue.

Just so I'm clear on understanding the issue: 
-should the newly generalised schedule you're requesting remain within `Step.hs`? 
or (if `Step n` needs to be a type signature of CycleClock)
-should the contents of `Step.hs` be refactored into `Cycle.hs` (including the newly generalised schedule)?

thank you!

**Comment by turion** [comment]
Great! For now, it's best to just touch Cycle.hs and add a schedule there. As soon as we have this, we can figure out how to proceed with Step.hs.

**Comment by turion** [comment]
There is going to be a big rename, which also touches `Cycle` and `Step`. The PR is probably going to be merged soon. This will probably cause merge conflicts with whatever you have so far. But don't worry about it, I can address the conflicts if it gets too complicated.

**Comment by turion** [comment]
Are you still working on this? I'm considering to close this issue in favour of #73.

**Comment by SolviQorda** [comment]
Hey,

I am working on it, but not getting very far - if you're thinking about closing it for #73 then that's understandable!

**Comment by turion** [comment]
Maybe it's best to give this issue a pause until #73 is settled :) I realised myself that it's not as easy as I thought in the beginning.

**Comment by turion** [comment]
And I just realised that `Periodic` is already in `ScheduleT`, thus it doesn't need its own schedule. Sorry about the mess, I wasn't careful when I opened this issue.

**Comment by SolviQorda** [comment]
No worries! :) thanks for being understanding.
