### ISSUE TITLE
Bounded FIFO & LIFO buffers

### ISSUE THREAD

**Issue by turion** [turion/rhine#53]
For the `fifo` and `lifo` buffers, implement a bounded version that forgets the oldest values when the size is above a given threshold.

**Comment by SolviQorda** [comment]
Hi! I've had a go at this and I have a solution that compiles. However, I'm not entirely sure about the best way to test it. Should I make the PR anyway?

**Comment by turion** [comment]
You can create test cases with pure clocks (e.g. `FixedStep`). Do submit the PR anyway, it should be feasible to see correctness for components of this size.
