### ISSUE TITLE
Space leak in ResamplingBuffers

### ISSUE THREAD

**Issue by turion** [turion/rhine#55]
It's possible to build an unintended space leak in a resampling buffer if data is produced very quickly and accumulates on the buffer. So far that's not surprising, for some buffers (i.e. collect, unbounded queues), that's what has to be expected.

I'm annoyed that it's also possible to create space leaks unintentionally. There is an example in https://github.com/turion/rhine/tree/dev_spaceleak. On one clock, a lot of numbers are produced, and sent to the buffer in order to be added there. On the other clock, the current sum is retrieved. In principle, it should be possible to just add the numbers up strictly, but it's not obvious to me how to achieve that.

**Comment by ivanperez-keera** [comment]
> It's possible to build an unintended space leak in a resampling buffer if data is produced very quickly and accumulates on the buffer. So far that's not surprising, for some buffers (i.e. collect, unbounded queues), 
that's what has to be expected.

Agreed.

I have tried the example and I do not see this leak.

**Comment by turion** [comment]
The branch https://github.com/turion/rhine/tree/dev_spaceleak indeed shows how to fix the leak by implementing the buffer in a particular way. So it's a library user issue for now.
