### ISSUE TITLE
Remove/refactor Count and FixedRate

### ISSUE THREAD

**Issue by turion** [turion/rhine#66]
* [ ] `FixedRate` is against the Rhine philosophy that sample rates should be type-level. There are better alternatives now (`Step`/`FixedStep`), and it should be removed.
* [ ] `Count` is just `Step 1`/`FixedStep 1`. Should be a type synonym, and moved into the `FixedStep` module.

**Comment by SolviQorda** [comment]
Hi again!

I _think_ I have a solution to this, but I'm concerned I may have underestimated the complexity of the issue...

For the first part I understood that to mean delete the module.

For the second part, the following compiles:
```type Count m cl = FixedStep 1```
though I'm concerned that's too simple a solution?

Happy to make a PR if that's easier!

**Comment by turion** [comment]
Yes, that's the idea, although you don't need those type parameters `m` and `cl`.

**Comment by turion** [comment]
Fixed by @SolviQorda in #84
