### ISSUE TITLE
Generalise ScheduleT to a type class

### ISSUE THREAD

**Issue by turion** [turion/rhine#87]
Common monad transformers like `ReaderT r` from `transformers` have a corresponding type class like `MonadReader r` from `mtl` that offers the interface of `ReaderT r`. The free monad transformer `ScheduleT` in `Control.Monad.Schedule` should have such a type class, `MonadSchedule` as well.

* [ ] Easy tasks:
  * [ ] Implement type class `MonadWait` with method `wait`
  * [ ] Implement type class `MonadSchedule` with method `race`
  * [ ] Make `ScheduleT` an instance of `MonadSchedule`
* [ ] Intermediate
  * [ ] Use threads and `MVar`s to make `IO`, or even `MonadIO` an instance of `MonadSchedule`.
  * [ ] Compare the universal schedule with `IO`s `MonadSchedule` class with the `concurrently schedule
  * [ ] Instances `MonadSchedule m => MonadSchedule (ReaderT r m)`, and for other transformers
* [ ] Hard
  * [ ] Read [Oleg Kiselyov's lecture notes on final tagless encoding](http://okmij.org/ftp/tagless-final/course/lecture.pdf)
  * [ ] Reimplement `race` in terms of `wait` (if this even works), that is, supply a default implementation of `race`

Any difficulty class of the above is already a useful contribution!

**Comment by turion** [comment]
Bonus question: Is the universal schedule from `IO`'s `MonadSchedule` as fast as the `concurrently` schedule from the library?

**Comment by turion** [comment]
## About free monads

You don't necessarily need to understand free monads in depth in order to tackle this issue. The bottom line is this:

* A functor encodes a side effect.
* A monad encodes side effects that can be "sequenced", i.e. multiple of them can be combined into one.
* A free monad over a functor takes arbitrarily many copies of the side effects of the functor and puts them in a kind of list, so they can be trivially sequenced (by concatenating lists).

So if we take the Wait functor which encodes the side effect of "_wait for a particular time and then return a value_", its free monad will encode side effects like "_wait for some time, do a computation, possibly wait some more, do another computation, possibly wait some more, etc., and finally return a value_".

**Comment by SolviQorda** [comment]
I'm still working on this - been plugging away for the last few days trying to make sure I understand what I'm trying to do, and get my head around the types.

This is my line of thinking at the moment.
1. The MonadWait and MonadSchedule typeclasses need to define wait and race, respectively.
2. race currently uses wait, so unless I need to refactor race to be polymorphic, then MonadSchedule needs to extend MonadWait, or define it's own wait.
3. The instance that defines how ScheduleT uses these typeclasses needs to define how those functions are called with ScheduleT.
4. Which suggests that the 2 typeclasses require less specific (more polymorphic?) definitions of wait and race than the ones that are in the module currently.

Does this sound like approximately the right track?

**Comment by turion** [comment]
1. Yes.
2. The former. You should have `class MonadWait m => MonadSchedule`.
3. Yes, I think we mean the same thing.
4. Yes, `wait` and `race` should be fully polymorphic in the monad.

**Comment by SolviQorda** [comment]
Amazing thank you!

**Comment by SolviQorda** [comment]
Hi, 

So I've been working on this for about 10 hours now, trying to build an understanding of transformers and interface typeclasses.

What I have below compiles, so I'm tentatively hoping that it's going in the right direction. I'm still working on the implementation of race in MonadSchedule. 

Should I submit this as a pull request, or keep working until I can get all the Easy to-do's compiling? I'm aware that this is possibly wrong but I also just wanted to communicate that I'm working on it!

```
class Monad m => MonadWait diff m | m -> diff where
-- | The side effect that waits for a specified amount.
    wait :: diff -> m ()
    wait diff = return ()

instance Monad m => MonadWait diff (ScheduleT diff m) where
    wait diff = FreeT $ return $ Free $ Wait diff $ return ()
```

**Comment by turion** [comment]
* Can you rewrite your `MonadWait` without the functional dependency?
* It's absolutely fine to just submit a pull request and work on that branch. Even if you upload wrong code that's no problem because once it's fixed I can squash all commits through github at the end.

**Comment by SolviQorda** [comment]
Cool ok thank you! I'll try and rewrite without the functional dependency and submit a PR :)

**Comment by turion** [comment]
You don't really need default instances like the one for `wait`. In fact I think it might be better if there is none.

**Comment by SolviQorda** [comment]
Oh ok! So would that mean that the 'old' implementation of wait needs to still be in there, just not within the instance?

**Comment by turion** [comment]
I meant the line `wait diff = return ()`. That allows users of the library to write `instance MonadWait MyDiff MyMonad where` without an actual implementation.

Your instance for `ScheduleT` looks fine.

**Comment by SolviQorda** [comment]
Ah I misunderstood, apologies. Will switch it back.

**Comment by turion** [comment]
Resolved in https://github.com/turion/rhine/pull/171
