### ISSUE TITLE
Haddocks for `@` etc. outdated

### ISSUE THREAD

**Issue by ggreif** [turion/rhine#88]
https://github.com/turion/rhine/blob/c4a44d73bfed22b2b9a4bb29073cb0db5a8c999c/rhine/src/FRP/Rhine/Reactimation/Combinators.hs#L7

**Comment by turion** [comment]
That's actually as intented. See e.g. http://hackage.haskell.org/package/rhine-0.4.0.0/docs/FRP-Rhine-SF-Combinators.html: I want to say that all combinators involving `@` annotate a data processing unit with a clocking unit. For example, `@@` annotates a `ClSF` with an atomic clock, `-@-` annotates a `ResamplingBuffer` with a `Schedule`, and so on. Or do you mean something else?

**Comment by ggreif** [comment]
Oh, then I misunderstood. I thought they are the actual operators. `@`
looked problematic to me because it is also used for visible type
application.

**Comment by turion** [comment]
Yes that's different, although somehow in a similar spirit.
