### ISSUE TITLE
Lifting Clocks with liftIO

### ISSUE THREAD

**Issue by ggreif** [turion/rhine#96]
I am toying around with using `threepenny-gui`s `UI` monad in `rhine`. Since it is a `newtype` of a `RWST`-transformed `IO` action, this should be possible. Maybe it can even be provided generically if the destination monad has a `MonadIO` instance. I'll try to come up with an answer for this...

**Comment by turion** [comment]
Isn't this what you need:
https://github.com/turion/rhine/blob/63fc173d93caea52cd2ec8d969f83ed3fbce433c/rhine/src/FRP/Rhine/Clock.hs#L256

**Comment by ggreif** [comment]
Yes, that did the trick! :-)
